#!/bin/bash
# Bundles the whole module into a single, self-contained installer script
# at dist/install-standalone.sh. Every file bin/, etc/, plugin/ and
# whm-plugin/ ship is embedded as base64 — the generated script needs no
# `git clone`, so it works from a private repo and can be hosted anywhere
# (your own domain, S3, a gist, etc.) and handed to anyone.
#
# Usage:
#   scripts/build-installer.sh
#   # then upload dist/install-standalone.sh to your web server
#
# Re-run this after every change to bin/, etc/, plugin/ or whm-plugin/ and
# re-upload — the standalone installer is a build artifact, not something
# you hand-edit.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$REPO_ROOT/dist"
OUT_FILE="$OUT_DIR/install-standalone.sh"

mkdir -p "$OUT_DIR"

# Every runtime file the module needs — everything except README/VERSION
# (not needed at runtime) and this build script / install.sh themselves.
FILES=(
  bin/backup-all.sh
  bin/backup-user.sh
  bin/restore-worker.sh
  bin/retention-cleanup.sh
  bin/s3-lib.sh
  etc/cron/skyserver-backup
  etc/logrotate/skyserver-backup
  etc/skyserver-backup.conf.example
  plugin/action.live.php
  plugin/index.live.php
  plugin/skyserver_backup.conf
  plugin/status.live.php
  scripts/uninstall.sh
  whm-plugin/index.cgi
  whm-plugin/skyserver_backup.appconfig
)

token_for() { echo "$1" | tr -c 'A-Za-z0-9' '_'; }

{
cat <<'HEADER'
#!/bin/bash
# SkyServer cPanel Backup Module — standalone installer (self-contained,
# no git/GitHub access required). Generated by scripts/build-installer.sh
# — do not edit by hand, edit the source files and rebuild instead.
#
# Run as root on the WHM/cPanel server you want to protect:
#
#   curl -sSL https://<your-domain>/install.sh | bash
set -euo pipefail

INSTALL_DIR="/opt/skyserver-backup-module"
CONF_FILE="/etc/skyserver-backup.conf"
DYNAMICUI_DIR="/var/cpanel/dynamicui"
FRONTEND_BASE="/usr/local/cpanel/base/frontend"
CRON_FILE="/etc/cron.d/skyserver-backup"
SPOOL_DIR="/var/spool/skyserver-backup"
WHM_CGI_DIR="/usr/local/cpanel/whostmgr/docroot/cgi/skyserver_backup"

log()  { echo "[skyserver-backup] $*"; }
die()  { echo "[skyserver-backup] ERROR: $*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ]        || die "This installer must be run as root."
[ -d /usr/local/cpanel ]    || die "cPanel/WHM installation not found at /usr/local/cpanel."

log "Installing dependencies (jq, awscli)..."
if command -v yum >/dev/null 2>&1; then
  yum install -y jq awscli >/dev/null 2>&1 || true
elif command -v dnf >/dev/null 2>&1; then
  dnf install -y jq awscli >/dev/null 2>&1 || true
elif command -v apt-get >/dev/null 2>&1; then
  apt-get update -y >/dev/null 2>&1 && apt-get install -y jq awscli >/dev/null 2>&1 || true
fi
command -v jq  >/dev/null 2>&1 || die "jq is required but could not be installed automatically."
command -v aws >/dev/null 2>&1 || die "AWS CLI is required but could not be installed automatically. Install it manually and re-run this script."

log "Writing module files to $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR"/bin "$INSTALL_DIR"/etc/cron "$INSTALL_DIR"/etc/logrotate "$INSTALL_DIR"/plugin "$INSTALL_DIR"/whm-plugin "$INSTALL_DIR"/scripts
HEADER

for f in "${FILES[@]}"; do
  token="$(token_for "$f")"
  echo
  echo "mkdir -p \"\$INSTALL_DIR/$(dirname "$f")\""
  echo "base64 -d > \"\$INSTALL_DIR/$f\" <<'FILE_${token}'"
  base64 "$REPO_ROOT/$f"
  echo "FILE_${token}"
done

cat <<'FOOTER'

chmod +x "$INSTALL_DIR"/bin/*.sh "$INSTALL_DIR"/scripts/*.sh

log "Setting up spool directories..."
mkdir -p "$SPOOL_DIR"/manifests "$SPOOL_DIR"/restore-requests "$SPOOL_DIR"/restore-status
chmod 750 "$SPOOL_DIR"

if [ ! -f "$CONF_FILE" ]; then
  cp "$INSTALL_DIR/etc/skyserver-backup.conf.example" "$CONF_FILE"
  chmod 600 "$CONF_FILE"
  log "Config file created at $CONF_FILE (S3 bucket + AWS keys are still placeholders)."
else
  log "Existing config found at $CONF_FILE — leaving it untouched."
fi

log "Installing cron jobs..."
sed "s#__INSTALL_DIR__#$INSTALL_DIR#g" "$INSTALL_DIR/etc/cron/skyserver-backup" > "$CRON_FILE"
chmod 644 "$CRON_FILE"

log "Installing log rotation..."
cp "$INSTALL_DIR/etc/logrotate/skyserver-backup" /etc/logrotate.d/skyserver-backup
chmod 644 /etc/logrotate.d/skyserver-backup

log "Installing cPanel end-user plugin into every theme..."
for THEME_DIR in "$FRONTEND_BASE"/*/; do
  [ -d "$THEME_DIR" ] || continue
  PLUGIN_DEST="${THEME_DIR}skyserver_backup"
  mkdir -p "$PLUGIN_DEST"
  cp "$INSTALL_DIR"/plugin/*.live.php "$PLUGIN_DEST/"
done
mkdir -p "$DYNAMICUI_DIR"
cp "$INSTALL_DIR/plugin/skyserver_backup.conf" "$DYNAMICUI_DIR/dynamicui_skyserver_backup.conf"

log "Installing WHM admin dashboard..."
PHP_BIN="$(command -v php || true)"
[ -z "$PHP_BIN" ] && [ -x /usr/local/cpanel/3rdparty/bin/php ] && PHP_BIN="/usr/local/cpanel/3rdparty/bin/php"
[ -n "$PHP_BIN" ] || die "No PHP binary found — required for the WHM admin dashboard."

mkdir -p "$WHM_CGI_DIR"
sed "1s|.*|#!${PHP_BIN}|" "$INSTALL_DIR/whm-plugin/index.cgi" > "$WHM_CGI_DIR/index.cgi"
chmod 750 "$WHM_CGI_DIR/index.cgi"
/usr/local/cpanel/bin/register_appconfig "$INSTALL_DIR/whm-plugin/skyserver_backup.appconfig" >/dev/null 2>&1 \
  || log "  (register_appconfig failed or is unavailable — add the WHM entry manually, see README)"

log "Rebuilding cPanel UI caches..."
/usr/local/cpanel/scripts/rebuild_sprites >/dev/null 2>&1 || true
/usr/local/cpanel/scripts/rebuildnavigations >/dev/null 2>&1 || true

echo
log "Install complete."
log "Next steps:"
log "  1) Edit $CONF_FILE — set S3_BUCKET, AWS_DEFAULT_REGION, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY"
log "     (or use the WHM admin dashboard's config form instead)."
log "  2) Test a manual backup run:  $INSTALL_DIR/bin/backup-all.sh"
log "  3) Daily backups then run automatically at 02:00 via /etc/cron.d/skyserver-backup."
log "  4) Admin: WHM → Plugins → SkyServer Backup Manager."
log "  5) Each cPanel user will see 'SkyServer Backup Manager' under the Files section."
log ""
log "Self-service restore is DISABLED by default. Verify a restore yourself on a"
log "throwaway account first, then enable it from the WHM dashboard's config form."
FOOTER
} > "$OUT_FILE"

chmod +x "$OUT_FILE"
echo "Built: $OUT_FILE ($(wc -l < "$OUT_FILE") lines, $(du -h "$OUT_FILE" | cut -f1))"
