#!/bin/bash
# Bundles the whole module into a single, self-contained installer script
# at dist/install-standalone.sh. Every runtime file is embedded as base64,
# so the generated script needs no `git clone` and works even against a
# private repo — host it anywhere and hand the URL to anyone.
#
# Usage:
#   scripts/build-installer.sh
#   # then upload dist/install-standalone.sh to your web server as
#   # https://backup.gosecureserver.in/install.sh
#
# Re-run this after changing anything under bin/, etc/, plugin/ or
# whm-plugin/ and re-upload — the standalone installer is a build
# artifact, not something you hand-edit.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$REPO_ROOT/dist"
OUT_FILE="$OUT_DIR/install-standalone.sh"

mkdir -p "$OUT_DIR"

# Every runtime file the module needs. VERSION is included so the WHM
# update check can compare against GitHub; README and this build script
# are not needed on a server.
FILES=(
  VERSION
  bin/backup-all.sh
  bin/backup-user.sh
  bin/deploy.sh
  bin/restore-worker.sh
  bin/retention-cleanup.sh
  bin/s3-lib.sh
  bin/self-update.sh
  etc/cron/skyserver-backup
  etc/logrotate/skyserver-backup
  etc/skyserver-backup.conf.example
  plugin/action.live.php
  plugin/index.live.php
  plugin/skyserver_backup.conf
  plugin/status.live.php
  scripts/uninstall.sh
  whm-plugin/index.cgi
  whm-plugin/skyserver_backup.appconfig
)

token_for() { echo "$1" | tr -c 'A-Za-z0-9' '_'; }

{
cat <<'HEADER'
#!/bin/bash
# SkyServer cPanel Backup Module — standalone installer (self-contained,
# no git/GitHub access required). Generated by scripts/build-installer.sh
# — do not edit by hand, edit the source files and rebuild instead.
#
# Run as root on the WHM/cPanel server you want to protect:
#
#   curl -sSL https://backup.gosecureserver.in/install.sh | bash
set -euo pipefail

INSTALL_DIR="/opt/skyserver-backup-module"

log()  { echo "[skyserver-backup] $*"; }
die()  { echo "[skyserver-backup] ERROR: $*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ]     || die "This installer must be run as root."
[ -d /usr/local/cpanel ] || die "cPanel/WHM installation not found at /usr/local/cpanel."

log "Installing dependencies (git, jq, awscli)..."
if command -v yum >/dev/null 2>&1; then
  yum install -y git jq awscli >/dev/null 2>&1 || true
elif command -v dnf >/dev/null 2>&1; then
  dnf install -y git jq awscli >/dev/null 2>&1 || true
elif command -v apt-get >/dev/null 2>&1; then
  apt-get update -y >/dev/null 2>&1 && apt-get install -y git jq awscli >/dev/null 2>&1 || true
fi
command -v jq  >/dev/null 2>&1 || die "jq is required but could not be installed automatically."
command -v aws >/dev/null 2>&1 || die "AWS CLI is required but could not be installed automatically. Install it manually and re-run this script."

log "Writing module files to $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR"/bin "$INSTALL_DIR"/etc/cron "$INSTALL_DIR"/etc/logrotate "$INSTALL_DIR"/plugin "$INSTALL_DIR"/whm-plugin "$INSTALL_DIR"/scripts
HEADER

for f in "${FILES[@]}"; do
  token="$(token_for "$f")"
  echo
  echo "mkdir -p \"\$INSTALL_DIR/$(dirname "$f")\""
  echo "base64 -d > \"\$INSTALL_DIR/$f\" <<'FILE_${token}'"
  base64 "$REPO_ROOT/$f"
  echo "FILE_${token}"
done

cat <<'FOOTER'

chmod +x "$INSTALL_DIR"/bin/*.sh "$INSTALL_DIR"/scripts/*.sh

# Everything below (config, cron, logrotate, both plugins) lives in
# deploy.sh so the installer and the in-place updater stay in step.
"$INSTALL_DIR/bin/deploy.sh"

echo
log "Install complete."
log "Next steps:"
log "  1) Edit /etc/skyserver-backup.conf — set S3_BUCKET, AWS_DEFAULT_REGION,"
log "     AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY (or use the WHM config form)."
log "  2) In WHM → Plugins → SkyServer Backup Manager, hit 'Test S3 Connection'."
log "  3) Back up a single account from the dashboard and check the result."
log "  4) Daily backups then run automatically at 02:00."
log ""
log "Self-service restore is DISABLED by default. Verify a restore yourself on a"
log "throwaway account first, then enable it from the WHM dashboard's config form."
FOOTER
} > "$OUT_FILE"

chmod +x "$OUT_FILE"
echo "Built: $OUT_FILE ($(wc -l < "$OUT_FILE") lines, $(du -h "$OUT_FILE" | cut -f1))"
